apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: wp-${wp_name}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: wp-${wp_name}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "wordpress"
        minAllowed:
          cpu: 50m
          memory: 128Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
        controlledResources: ["cpu", "memory"]
      - containerName: "metrics"
        minAllowed:
          cpu: 10m
          memory: 32Mi
        maxAllowed:
          cpu: 500m
          memory: 250Mi
        controlledResources: ["cpu", "memory"]
