apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wireguard-pre-deploy
  namespace: flux-system
spec:
  interval: 1h
  path: ./flux/extras/wireguard/pre-deploy
  force: true
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      create_dir_path: "/srv/wireguard"
      create_dir_pvc: "main-ad2"
      create_dir_proj_name: "wireguard"
