apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  path: "./flux/apps/cloud-demo-app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system