apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-demo-app
resources:
- ./prod/imageupdateautomation.yaml
- imagerepository.yaml
# - ./prod/oracle-registry-secret.yaml
- ./prod/imagepolicy.yaml
- ./prod/cloud-demo-app-ingress.yaml
- ./prod/cloud-demo-app-certificate.yaml
- ./prod/deployment.yaml
- ./prod/service.yaml
- namespace.yaml
