apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- imageupdateautomation.yaml
- imagerepository.yaml
- imagepolicy.yaml
- cloud-demo-app-ingress.yaml
- cloud-demo-app-certificate.yaml
- ./deploy/deployment.yaml
- ./deploy/service.yaml
- ./deploy/namespace.yaml