apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloud-demo-app-kustomization
  namespace: cloud-demo-app
spec:
  interval: 1m0s
  path: "./flux/apps/cloud-demo-app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
  target-namespace: cloud-demo-app