apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-demo-app
resources:
- imageupdateautomation.yaml
- imagerepository.yaml
- imagepolicy.yaml
- kustomization-cloud-demo-app.yaml
- ./deploy/deployment.yaml
- ./deploy/service.yaml