apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: ">=9.9.0"
      sourceRef:
        kind: HelmRepository
        name: vpa
        namespace: kube-system
  values:
    admissionController:
      metrics:
        serviceMonitor:
          enabled: true
    recommender:
      extraArgs:
        recommendation-lower-bound-cpu-percentile: "0.7"
        recommendation-lower-bound-memory-percentile: "0.7"
        pod-recommendation-min-cpu-millicores: 25
        pod-recommendation-min-memory-mb: 25
        recommender-name: performance
        memory-saver: true
      metrics:
        serviceMonitor:
          enabled: true
    updater:
      extraArgs:
        min-replicas: 1
      metrics:
        serviceMonitor:
          enabled: true
