apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '>=4.8.0'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: ingress-secgroup-oidc
  values:
    # based on https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
    controller:
      ingressClassResource:
        enabled: true
        name: nginx
        default: true
      minAvailable: 1
      replicaCount: 2
      service:
        enableHttp: true
        annotations:
          # based on: https://github.com/oracle/oci-cloud-controller-manager/blob/master/docs/load-balancer-annotations.md
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
