apiVersion: v1
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: monitoring
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: prom-stack-grafana-pass
    namespace: monitoring
type: Opaque
data:
    values.yaml: ENC[AES256_GCM,data:i+oZB1M3baefSHwrWMe0iT46Jw+DvNmjgQ9thUew27mUkRXQ2ryqNFnraM8=,iv:T2I+yBJikxUdIdt9zXlwoVxG7kmgdD5yymVzAsqb4xE=,tag:Nyo845iiQme4B2sFUKJUbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-13T02:03:44Z"
    mac: ENC[AES256_GCM,data:goSFSyczckeJKaZ1yvODetvG4wQuoOzYJADFa31CruI2LTxIdSqup3h58iTVA/gCH1t7rVZW8NPI1/bjMFoGEayfdqQZrF8lpXYG//Uao5bJJeETMpxPEck/GVxd/HZsXcPKBJZe+I9vyIdQyg2E6UqT32OMYJX8FNGRKgK1bLA=,iv:9pXkN1u5zCgt5fowQyvUAoWYBcJ7JvF5sTMJb0NHg+A=,tag:Y5S1Qgk3Dtx9LTWEbrgptA==,type:str]
    pgp:
        - created_at: "2025-03-13T02:03:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5eHL2SnBXSeAQ/+NUYT3mFBTCxM/OpmxsZMRYe0PYLzxT3wmbIt0crWEDzO
            /dWq9myr9ExyHvPSpE33xghSChydbfVLHaa+bEXSmHD3sMk6gIbCH+TBcvhQpcAo
            4WDb/uiRprD4fNl6whAeNK4PeKumiU45CIfRMZm3gd0uOHqhAfSyc5nZ4ZBbj24N
            CKczqIB6U8OxpgzzFK30hreI0VJfYvI26RvtQUz6kT+0hq6eDlIU+mlMWkVTRMNR
            tSL3YF+v93glylfObMe8QMBIj7bZ6Tlbgr+e6xsJfAGkN9gGktNfFAD3/V5haZ8G
            pMpiPZQdFkSWhZF4SkhJrmm/MN6L7K2tMZZ4noTEDX8WcwoUGi6a5GzSGUF1IM/W
            Dj7e77djXj7zQb7wT8SfmOOaK07J/qt96n/tbW0bX0r3XoJCJ6WJR0AONJL5W09p
            PxPGgfBhZu8fRv85imcvltnrQ5hDP52wxFCoNB9FMIFRwcQ7p8aKv5z3LeRQyLHd
            IrOUCQ5WZOCeGApMmitrbfiVaOL/zVIzByH6mMFbiiWfKaoZ6XNb+UkiOhldf/bM
            UDDf9xrtEOfshPFCyFt4q2HjNaPCceryPoCZ2E+DHXpk60y1J8UZBgJ2aOzlvuy6
            6UeJsQhgj3HsQLQTlIfOsXiVgFkTPhgSHjFb0DgVD1RjmrYqOtR2p7uGGTWPAnXU
            aAEJAhD1ZDJPDaqbdTTB9/XKNoiLM1qrdD9TC/CgvJOdlcJc2wOL6LZ8IkJpoIhx
            1j6snA2AdGcS1I1vHFfPtb2jCbetINES5zkW/uUg0HRrP2+c2eqsU4jFitiJfgOu
            Mq3qPNl0MsFF
            =yLWB
            -----END PGP MESSAGE-----
          fp: 98631BFF44F654007512F8BA33B65FC6B6166E6D
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
