apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-demo-app-TST-crt
  namespace: cloud-demo-app
spec:
  secretName: cloud-demo-app-TST-tls
  dnsNames:
  - cloud-app.farted.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer