apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cloud-demo-app-TST-image-policy
  namespace: cloud-demo-app
spec:
  imageRepositoryRef:
    name: cloud-demo-app-image-repository
  filterTags:
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc